
package jaxws.giro;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GiroServiceImplService", targetNamespace = "http://giro.jaxws/", wsdlLocation = "http://airdev.nl:9090/giro?wsdl")
public class GiroServiceImplService
    extends Service
{

    private final static URL GIROSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GIROSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GIROSERVICEIMPLSERVICE_QNAME = new QName("http://giro.jaxws/", "GiroServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://airdev.nl:9090/giro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GIROSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GIROSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GiroServiceImplService() {
        super(__getWsdlLocation(), GIROSERVICEIMPLSERVICE_QNAME);
    }

    public GiroServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GIROSERVICEIMPLSERVICE_QNAME, features);
    }

    public GiroServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GIROSERVICEIMPLSERVICE_QNAME);
    }

    public GiroServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GIROSERVICEIMPLSERVICE_QNAME, features);
    }

    public GiroServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GiroServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GiroServiceImpl
     */
    @WebEndpoint(name = "GiroServiceImplPort")
    public GiroServiceImpl getGiroServiceImplPort() {
        return super.getPort(new QName("http://giro.jaxws/", "GiroServiceImplPort"), GiroServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GiroServiceImpl
     */
    @WebEndpoint(name = "GiroServiceImplPort")
    public GiroServiceImpl getGiroServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://giro.jaxws/", "GiroServiceImplPort"), GiroServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GIROSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GIROSERVICEIMPLSERVICE_EXCEPTION;
        }
        return GIROSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
